// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {auth} from '../models';
import {logger} from '../models';
import {main} from '../models';

export function CancelCodexAuth(arg1:string):Promise<void>;

export function ClearCooldown(arg1:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<config.Account>>;

export function GetCodexAuthSession(arg1:string):Promise<auth.CodexAuthSessionView>;

export function GetHostName():Promise<string>;

export function GetLogs(arg1:number):Promise<Array<logger.Entry>>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function GetState():Promise<main.State>;

export function ImportAccounts(arg1:Array<config.Account>):Promise<number>;

export function OpenDataDir():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function RefreshAccount(arg1:string):Promise<void>;

export function RefreshAllQuotas():Promise<void>;

export function RefreshQuota(arg1:string):Promise<void>;

export function SetAllowLAN(arg1:boolean):Promise<void>;

export function SetAutoStartProxy(arg1:boolean):Promise<void>;

export function SetProxyPort(arg1:number):Promise<void>;

export function StartCodexAuth():Promise<auth.CodexAuthStart>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function SyncCodexAccountToCodexCLI(arg1:string):Promise<auth.CodexAuthSyncResult>;

export function SyncCodexAccountToKiloAuth(arg1:string):Promise<auth.KiloAuthSyncResult>;

export function SyncCodexAccountToOpencodeAuth(arg1:string):Promise<auth.OpencodeAuthSyncResult>;

export function ToggleAccount(arg1:string,arg2:boolean):Promise<void>;
