// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCodexAuth(arg1) {
  return window['go']['main']['App']['CancelCodexAuth'](arg1);
}

export function ClearCooldown(arg1) {
  return window['go']['main']['App']['ClearCooldown'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetCodexAuthSession(arg1) {
  return window['go']['main']['App']['GetCodexAuthSession'](arg1);
}

export function GetHostName() {
  return window['go']['main']['App']['GetHostName']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportAccounts(arg1) {
  return window['go']['main']['App']['ImportAccounts'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function RefreshAccount(arg1) {
  return window['go']['main']['App']['RefreshAccount'](arg1);
}

export function RefreshAllQuotas() {
  return window['go']['main']['App']['RefreshAllQuotas']();
}

export function RefreshQuota(arg1) {
  return window['go']['main']['App']['RefreshQuota'](arg1);
}

export function SetAllowLAN(arg1) {
  return window['go']['main']['App']['SetAllowLAN'](arg1);
}

export function SetAutoStartProxy(arg1) {
  return window['go']['main']['App']['SetAutoStartProxy'](arg1);
}

export function SetProxyPort(arg1) {
  return window['go']['main']['App']['SetProxyPort'](arg1);
}

export function StartCodexAuth() {
  return window['go']['main']['App']['StartCodexAuth']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function SyncCodexAccountToCodexCLI(arg1) {
  return window['go']['main']['App']['SyncCodexAccountToCodexCLI'](arg1);
}

export function SyncCodexAccountToKiloAuth(arg1) {
  return window['go']['main']['App']['SyncCodexAccountToKiloAuth'](arg1);
}

export function SyncCodexAccountToOpencodeAuth(arg1) {
  return window['go']['main']['App']['SyncCodexAccountToOpencodeAuth'](arg1);
}

export function ToggleAccount(arg1, arg2) {
  return window['go']['main']['App']['ToggleAccount'](arg1, arg2);
}
